default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgres
  password:
  host: db
  database: deep_space_9_development

test:
  <<: *default
  username: postgres
  password:
  host: db
  database: deep_space_9_test